#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROFILE="${NATIVE_BUILD_PROFILE:-development}"
ENV_FILE="${ROOT}/.env"

if [ "$PROFILE" = "production" ]; then
  if [ -f "${ROOT}/.env.production" ]; then
    ENV_FILE="${ROOT}/.env.production"
  else
    echo "Saknar .env.production — kopiera från .env.production.example" >&2
    exit 1
  fi
fi

if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$ENV_FILE"
  set +a
fi

export NATIVE_BUILD_PROFILE="$PROFILE"
bash "${ROOT}/scripts/apply-native-build-profile.sh"

FRONTEND_DIR="${ROOT}/.frontend/bilenia-dealer-panel"
OUT_DIR_NAME="${FRONTEND_OUT_DIR:-dist}"
FRONTEND_OUT="${FRONTEND_DIR}/${OUT_DIR_NAME}"

if [ ! -d "$FRONTEND_DIR" ]; then
  echo "Saknar frontend. Kör först: npm run fetch:frontend" >&2
  exit 1
fi

cd "$FRONTEND_DIR"

# Bake mobile API URLs from https-app .env into Vite capacitor mode build
if [ -f "$ENV_FILE" ]; then
  {
    echo "# Auto-generated by build-web.sh — do not commit from .frontend"
    grep -E '^VITE_' "$ENV_FILE" || true
  } > .env.capacitor
  echo "Skrev .env.capacitor för mobil-build (${PROFILE}) från ${ENV_FILE}"
fi

npm ci
npm run build:mobile

if [ ! -d "$FRONTEND_OUT" ]; then
  echo "Hittade inte build-output: ${FRONTEND_OUT}" >&2
  echo "Sätt FRONTEND_OUT_DIR om appen bygger till annat än dist/ (t.ex. build)." >&2
  exit 1
fi

rm -rf "${ROOT}/www"
cp -R "$FRONTEND_OUT" "${ROOT}/www"

# Source maps are not used in the WebView and bloat APK size / emulator memory.
find "${ROOT}/www" -name '*.map' -delete
echo "Tog bort source maps från www/"

bash "${ROOT}/scripts/patch-www-mobile.sh"
node "${ROOT}/scripts/generate-native-assets.js"
